### ISSUE TITLE
An error occurred while reading the .pth file

### ISSUE THREAD

**Issue by zzhonghan** [lexiaoheng/Mariana#1]
hello. When I read <BestModel.pth>, I got an error '_pickle.UnpicklingError: invalid load key, 'v'.'. 
I checked the python and Pytorch versions and they are the same as you requested. 
Is the.pth file corrupted?

**Comment by zzhonghan** [comment]
Here's the full traceback：

Traceback (most recent call last):
  File "G:/Mariana-main/NoiseAttenuation/diffusion_model/diffusion_model/main.py", line 79, in <module>
    DDPM.load_state_dict(torch.load(best_model_path))
  File "G:\Anaconda3\envs\Mariana-main\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "G:\Anaconda3\envs\Mariana-main\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

ask for your help.
